name: Build Unity Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - uses: game-ci/unity-builder@v2
      with:
        unityVersion: 2021.3.18f1
        targetPlatform: StandaloneWindows64
        buildMethod: BuildScript.BuildWindows

    - uses: actions/upload-artifact@v3
      with:
        name: Build
        path: build/